const iconMap = {
  add: 'pi pi-plus',
  edit: 'pi pi-pencil',
  delete: 'pi pi-trash',
  refresh: 'pi pi-refresh',
  download: 'pi pi-download',
  print: 'pi pi-print',
  search: 'pi pi-search',
  pdf: 'pi pi-file-pdf',
  calendar: 'pi pi-calendar',
  login: 'pi pi-sign-in',
  save: 'pi pi-save',
  key: 'pi pi-key',
  check: 'pi pi-check',
  employees: 'pi pi-users',
  employee: 'pi pi-user',
  home: 'pi pi-home',
  list: 'pi pi-list',
  info: 'pi pi-info-circle',
  email: 'pi pi-envelope',
  phone: 'pi pi-phone',
  id: 'pi pi-id-card',
  cancel: 'pi pi-times',
  minus: 'pi pi-minus',
  signout: 'pi pi-sign-out',
  login: 'pi pi-sign-in',
  vendor: 'pi pi-building',
  box: 'pi pi-box',
  tags: 'pi pi-tags',
  bom: 'pi pi-sitemap',
  inventory: 'pi pi-th-large',
  address: 'pi pi-map-marker',
  account: 'pi pi-shield',
  clip: 'pi pi-paperclip',
  openfolder: 'pi pi-folder-open',
  checksquere: 'pi pi-check-square',
  history: 'pi pi-history',
  undo: 'pi pi-undo',
  truck: 'pi pi-truck',
  send: 'pi pi-send',
  file: 'pi pi-file',
  pay: 'pi pi-credit-card',
  setting: 'pi pi-cog',
  pos: 'pi pi-desktop',
  dollar: 'pi pi-dollar',
  cart: 'pi pi-shopping-cart',
  chart: 'pi pi-chart-bar',
  wrench: 'pi pi-wrench',
  excel: 'pi pi-file-excel',
  pdf: 'pi pi-file-pdf'
};

export const useIcon = (name) => {
  return iconMap[name];
};
