server:
  port: 8080

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(vAsvZ1mSBtSB+7c6R+z5irmCN3mdtJRC4bx4luOiLFI7hWaaVgmiFLxqqQFRKKh4YpE4He94Bdc=)
    username: ENC(+lq0h68ay/lVnja2fzgZOXFw3FJZerRd)
    password: ENC(6hF3NHbh9t71GYf+Bf1FTRFRRP34aXcu)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(7JDPnrAIRt4K+W8VSzUhVMqKrhbSzM0mUoW+mEDG4pLmHs5cNTD8U0wvslYwfO9e)
    password: ENC(v/5eQe9/43OFw1neIM6TSJa2Csj4sJJs47fTCzLhrxY=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format-sql: true
    hibernate:
      ddl-auto: create
    show-sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: VARCHAR
  type-aliases-package: com.yedam.scm
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    root: INFO
    log4jdbc.log4j2: WARN
    jdbc:
      resultset: OFF
      sqltiming: WARN
    com.zaxxer.hikari: WARN

file:
  upload:
    employee-dir: C:/uploads/employee # 개발 환경
    # employee-dir: /home/app/uploads/employee  # 배포 환경
    defect-dir: C:/uploads/defect/

jwt:
  secret: ENC(dzfcQtWysP6YaJ/3ZshuUyeqb/Jqc23jSsctfL6ZfFEZHFBIOtIJIvjoknh2MiWnPQN3a2bYnUxzSV51QCoQ0A==)
  expiration: 18000000

# 아임포트 설정 은경
iamport:
  api:
    key: 6222787125430866
    secret: ENC(o3uRYlEvP8+RYBqiN+OpqY+r2Worq26zcZ1D9mBX2dqNBwL+FAH3rSTId12Ysvtq5IFDSb5HGglTpgmCgBF+tRZpS69ZPHuzi8Y0XPTnb5dW9D94XfYEBq0AXKr2XOHJ)

recaptcha:
  secret: ENC(zLwiX/LhEU83nbjggue9DwY5fObo+LNsjThVngMWZTa/TAGBTqXx0itpNH4Y10HplpqrHVppJXA=)

kakao:
  client:
    key: ENC(N3XaOG+/y9q1lWNAhCQEw3jUZulEkGqDEHkAVX6ROKJImTLdXCo9nkWh0wxItLFy)
