server:
  port: 8080

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(vAsvZ1mSBtSB+7c6R+z5irmCN3mdtJRC4bx4luOiLFI7hWaaVgmiFLxqqQFRKKh4YpE4He94Bdc=)
    username: ENC(+lq0h68ay/lVnja2fzgZOXFw3FJZerRd)
    password: ENC(6hF3NHbh9t71GYf+Bf1FTRFRRP34aXcu)

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format-sql: true
    hibernate:
      ddl-auto: create
    show-sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: VARCHAR
  type-aliases-package: com.yedam.scm
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    jdbc:
      resultset: off
      sqltiming: info
    com:
      example:
        demo: debug
    root: info
